<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;

class Users extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'organization_id',
        'name',
        'email',
        'password',
        'phone',
        'role',
        'avatar',
        'is_active',
    ];

    /**
     * The attributes that should be cast.
     */
    protected $casts = [
        'organization_id' => 'integer',
        'is_active' => 'boolean',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'deleted_at' => 'datetime',
    ];

    /**
     * The attributes that should be hidden for serialization.
     */
    protected $hidden = [
        'password',
    ];

    // ============ RELATIONSHIPS ============
    public function organizations()
    {
        return $this->belongsTo(Organizations::class);
    }

    // teachers
    public function teachers()
    {
        return $this->hasOne(Teachers::class, 'user_id');
    }

    /**
     * Get the assignments created by this user.
     */
    public function createdAssignments()
    {
        return $this->hasMany(Assignments::class, 'created_by');
    }

    /**
     * Get the files uploaded by this user.
     */
    public function files()
    {
        return $this->hasMany(Files::class, 'uploaded_by');
    }

    /**
     * Get the reports generated by this user.
     */
    public function reports()
    {
        return $this->hasMany(Reports::class, 'generated_by');
    }
}
